import type { ClothingItem } from '@/lib/types';

// Demo wardrobe items using Pexels stock photos
// These are used to seed a new user's wardrobe so the app is immediately useful
export const DEMO_ITEMS: Omit<ClothingItem, 'id' | 'user_id' | 'created_at' | 'updated_at'>[] = [
  {
    name: 'White Oxford Shirt',
    category: 'tops',
    subcategory: 'shirt',
    color: 'white',
    pattern: 'solid',
    material: 'cotton',
    style: 'classic',
    formality: 'smart casual',
    weather_suitability: ['mild', 'cold'],
    season: ['spring', 'autumn', 'winter'],
    brand: null,
    image_url: 'https://images.pexels.com/photos/9594086/pexels-photo-9594086.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    status: 'clean',
    wear_count: 0,
    last_worn: null,
    notes: null,
  },
  {
    name: 'Navy T-Shirt',
    category: 'tops',
    subcategory: 't-shirt',
    color: 'navy',
    pattern: 'solid',
    material: 'cotton',
    style: 'casual',
    formality: 'casual',
    weather_suitability: ['mild', 'hot'],
    season: ['spring', 'summer'],
    brand: null,
    image_url: 'https://images.pexels.com/photos/34156905/pexels-photo-34156905.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    status: 'clean',
    wear_count: 0,
    last_worn: null,
    notes: null,
  },
  {
    name: 'Black T-Shirt',
    category: 'tops',
    subcategory: 't-shirt',
    color: 'black',
    pattern: 'solid',
    material: 'cotton',
    style: 'casual',
    formality: 'casual',
    weather_suitability: ['mild', 'hot'],
    season: ['spring', 'summer', 'autumn'],
    brand: null,
    image_url: 'https://images.pexels.com/photos/5746098/pexels-photo-5746098.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    status: 'clean',
    wear_count: 0,
    last_worn: null,
    notes: null,
  },
  {
    name: 'Light Blue Jeans',
    category: 'bottoms',
    subcategory: 'jeans',
    color: 'light blue',
    pattern: 'solid',
    material: 'denim',
    style: 'casual',
    formality: 'casual',
    weather_suitability: ['mild', 'cold'],
    season: ['spring', 'autumn', 'winter'],
    brand: null,
    image_url: 'https://images.pexels.com/photos/17720437/pexels-photo-17720437.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    status: 'clean',
    wear_count: 0,
    last_worn: null,
    notes: null,
  },
  {
    name: 'Dark Denim Jeans',
    category: 'bottoms',
    subcategory: 'jeans',
    color: 'navy',
    pattern: 'solid',
    material: 'denim',
    style: 'smart casual',
    formality: 'smart casual',
    weather_suitability: ['mild', 'cold'],
    season: ['autumn', 'winter'],
    brand: null,
    image_url: 'https://images.pexels.com/photos/17720471/pexels-photo-17720471.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    status: 'clean',
    wear_count: 0,
    last_worn: null,
    notes: null,
  },
  {
    name: 'Teal Sneakers',
    category: 'shoes',
    subcategory: 'sneakers',
    color: 'teal',
    pattern: 'solid',
    material: 'leather',
    style: 'casual',
    formality: 'casual',
    weather_suitability: ['mild', 'hot'],
    season: ['spring', 'summer', 'autumn'],
    brand: null,
    image_url: 'https://images.pexels.com/photos/27503504/pexels-photo-27503504.png?auto=compress&cs=tinysrgb&h=650&w=940',
    status: 'clean',
    wear_count: 0,
    last_worn: null,
    notes: null,
  },
  {
    name: 'White Sneakers',
    category: 'shoes',
    subcategory: 'sneakers',
    color: 'white',
    pattern: 'solid',
    material: 'leather',
    style: 'casual',
    formality: 'casual',
    weather_suitability: ['mild', 'hot'],
    season: ['spring', 'summer'],
    brand: null,
    image_url: 'https://images.pexels.com/photos/12628400/pexels-photo-12628400.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    status: 'clean',
    wear_count: 0,
    last_worn: null,
    notes: null,
  },
  {
    name: 'Black Leather Sneakers',
    category: 'shoes',
    subcategory: 'sneakers',
    color: 'black',
    pattern: 'solid',
    material: 'leather',
    style: 'smart casual',
    formality: 'smart casual',
    weather_suitability: ['mild', 'cold'],
    season: ['autumn', 'winter'],
    brand: null,
    image_url: 'https://images.pexels.com/photos/27503498/pexels-photo-27503498.png?auto=compress&cs=tinysrgb&h=650&w=940',
    status: 'clean',
    wear_count: 0,
    last_worn: null,
    notes: null,
  },
  {
    name: 'Floral Casual Outfit',
    category: 'dresses',
    subcategory: 'casual dress',
    color: 'white',
    pattern: 'floral',
    material: 'cotton',
    style: 'casual',
    formality: 'casual',
    weather_suitability: ['mild', 'hot'],
    season: ['spring', 'summer'],
    brand: null,
    image_url: 'https://images.pexels.com/photos/12389578/pexels-photo-12389578.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    status: 'clean',
    wear_count: 0,
    last_worn: null,
    notes: null,
  },
  {
    name: 'White Sweater',
    category: 'outerwear',
    subcategory: 'sweater',
    color: 'white',
    pattern: 'solid',
    material: 'wool',
    style: 'casual',
    formality: 'smart casual',
    weather_suitability: ['cold'],
    season: ['autumn', 'winter'],
    brand: null,
    image_url: 'https://images.pexels.com/photos/9594086/pexels-photo-9594086.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    status: 'clean',
    wear_count: 0,
    last_worn: null,
    notes: null,
  },
];
